cow: true
pig: true
chicken: true
mooshroom: true
squid: true
wolf: true
ocelot: true
horse: true
villager: true
creeper: true
zombie: true
skeleton: true
spider: true
slime: true
ghast: true
pigman: true
enderman: true
cavespider: true
silverfish: true
blaze: true
magmacube: true
bat: true
witch: true
snowgolem: true
irongolem: true
giant: true
wither: true
enderdragon: true